apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rdsinstances.intive.com
spec:
  group: intive.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbName:
                  type: string
                instanceType:
                  type: string
                engine:
                  type: string
                stage:
                  type: string
                username:
                  type: string
                passwordSecretRef:
                  type: string
                region:
                  type: string
  scope: Namespaced
  names:
    plural: rdsinstances
    singular: rdsinstance
    kind: RDSInstance
    shortNames:
    - rds