apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rds-operator-clusterrole
rules:
- apiGroups: ["intive.com"]
  resources: ["rdsinstances"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]