---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-operator
  namespace: rds-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rds-operator
  template:
    metadata:
      labels:
        app: rds-operator
    spec:
      serviceAccountName: rds-operator
      containers:
      - name: rds-operator
        image: ghcr.io/intive/technical_challenge_apr2025_task03:1.0-dev-1
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: "eu-central-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret_key
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
