apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-operator
  namespace: rds-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rds-operator
  template:
    metadata:
      labels:
        app: rds-operator
    spec:
      serviceAccountName: rds-operator
      containers:
      - name: rds-operator
        image: intive.com/rds-operator:7
        imagePullPolicy: Never
        env:
        - name: AWS_REGION
          value: "eu-central-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret_key