apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-a
resources:
- ../common
- rbac.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/eventSources
      value:
      - kind: Kustomization
        name: tenant-a
        namespace: tenant-a
  target:
    group: notification.toolkit.fluxcd.io
    version: v1beta3
    kind: Alert
- path: notifications-patch.yaml
- path: sync-patch.yaml
labels:
- includeSelectors: true
  pairs:
    toolkit.fluxcd.io/tenant: tenant-a
