---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: repository
spec:
  url: https://git.org.com/tenant-a
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repository-sync
spec:
  serviceAccountName: tenant-a
  commonMetadata:
    labels:
      toolkit.fluxcd.io/tenant: tenant-a
