---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: repository
spec:
  url: ssh://git@github.com/intive/technical_challenge_apr2025.git
  ref:
    branch: dpildner
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repository-sync
spec:
  serviceAccountName: tenant-a
  commonMetadata:
    labels:
      toolkit.fluxcd.io/tenant: tenant-a
