---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.intive.com
spec:
  group: intive.com
  names:
    plural: kafkatopics
    singular: kafkatopic
    kind: KafkaTopic
    shortNames:
      - ktopic
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                partitions:
                  type: integer
                  description: "Number of partitions (immutable)"
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.partitions is immutable and cannot be updated"
                replicationFactor:
                  type: integer
                  description: "Replication factor (immutable)"
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.replicationFactor is immutable and cannot be updated"
                config:
                  type: object
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.config is immutable and cannot be updated"                  
                  additionalProperties:
                    type: string
                  description: "Kafka topic configuration"
              required: ["partitions", "replicationFactor"]

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaacls.intive.com
spec:
  group: intive.com
  names:
    plural: kafkaacls
    singular: kafkaacl
    kind: KafkaACL
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                principal:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.principal is immutable"
                operation:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.operation is immutable"
                resourceType:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.resourceType is immutable"
                resourceName:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.resourceName is immutable"
                patternType:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.patternType is immutable"
                host:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.host is immutable"
                permissionType:
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "spec.permissionType is immutable"
              required: ["principal", "operation", "resourceType", "resourceName"]
