apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-crd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-crd-operator
subjects:
  - kind: ServiceAccount
    name: kafka-crd-operator
    namespace: kafka-crd
