apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-crd-operator
  namespace: kafka-crd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-crd-operator
  template:
    metadata:
      labels:
        app: kafka-crd-operator
    spec:
      serviceAccountName: kafka-crd-operator
      containers:
        - name: kafka-operator
          image: ghcr.io/intive/technical_challenge_apr2025_task01:1.0-dev.10
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP
              value: "<change_me>" # comma separated list of brokers
            - name: KAFKA_CA_CERT
              value: "/etc/ssl/certs/ca-certificates.crt"
            - name: KAFKA_CLIENT_CERT
              value: "/certs/client.crt"
            - name: KAFKA_CLIENT_KEY
              value: "/certs/client.key"
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: certs
          secret:
            secretName: kafka-certs
            items:
              - key: client.crt
                path: client.crt
              - key: client.key
                path: client.key
