apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: pagerduty-alert
spec:
  providerRef:
    name: pagerduty-provider
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: <tenant-kustomization>
      namespace: <tenant-namespace>
